# Generated by Django 6.0.4 on 2026-05-07 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covoiturage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='prenom',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='id_reserv',
        ),
        migrations.AddField(
            model_name='etudiant',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
