# Generated by Django 6.0.4 on 2026-05-07 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covoiturage', '0002_remove_etudiant_nom_remove_etudiant_prenom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='photo',
            field=models.ImageField(default='profiles/default.png', upload_to='profiles/'),
        ),
    ]
