# Generated by Django 6.0.4 on 2026-05-08 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covoiturage', '0003_etudiant_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='trajet',
            name='prix',
            field=models.DecimalField(decimal_places=2, default=30, max_digits=6),
            preserve_default=False,
        ),
    ]
